"""Add kismet import tables

Revision ID: 5c2915c81bb9
Revises: allow_unlinked_client_observations
Create Date: 2026-07-23 12:29:08.546914+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2915c81bb9'
down_revision: Union[str, Sequence[str], None] = '84f6629b042f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('bssid', sa.String(length=32), nullable=False),
    sa.Column('ssid', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('client_vendor', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('signal_dbm', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_observations_bssid'), 'client_observations', ['bssid'], unique=False)
    op.create_index(op.f('ix_client_observations_client_mac'), 'client_observations', ['client_mac'], unique=False)
    op.create_index(op.f('ix_client_observations_id'), 'client_observations', ['id'], unique=False)
    op.create_index(op.f('ix_client_observations_survey_id'), 'client_observations', ['survey_id'], unique=False)
    op.create_index(op.f('ix_client_observations_timestamp'), 'client_observations', ['timestamp'], unique=False)
    op.create_table('device_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_profiles_client_mac'), 'device_profiles', ['client_mac'], unique=True)
    op.create_index(op.f('ix_device_profiles_id'), 'device_profiles', ['id'], unique=False)
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_name', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('inserted_records', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batch_id'), 'import_batch', ['id'], unique=False)
    op.create_index(op.f('ix_import_batch_survey_id'), 'import_batch', ['survey_id'], unique=False)
    op.create_table('observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('bssid', sa.String(), nullable=True),
    sa.Column('ssid', sa.String(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('signal_dbm', sa.Integer(), nullable=True),
    sa.Column('encryption', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_bssid'), 'observation', ['bssid'], unique=False)
    op.create_index(op.f('ix_observation_id'), 'observation', ['id'], unique=False)
    op.create_index(op.f('ix_observation_import_batch_id'), 'observation', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_observation_survey_id'), 'observation', ['survey_id'], unique=False)
    op.create_index(op.f('ix_observation_timestamp'), 'observation', ['timestamp'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_observation_timestamp'), table_name='observation')
    op.drop_index(op.f('ix_observation_survey_id'), table_name='observation')
    op.drop_index(op.f('ix_observation_import_batch_id'), table_name='observation')
    op.drop_index(op.f('ix_observation_id'), table_name='observation')
    op.drop_index(op.f('ix_observation_bssid'), table_name='observation')
    op.drop_table('observation')
    op.drop_index(op.f('ix_import_batch_survey_id'), table_name='import_batch')
    op.drop_index(op.f('ix_import_batch_id'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.drop_table('survey')
    op.drop_index(op.f('ix_device_profiles_id'), table_name='device_profiles')
    op.drop_index(op.f('ix_device_profiles_client_mac'), table_name='device_profiles')
    op.drop_table('device_profiles')
    op.drop_index(op.f('ix_client_observations_timestamp'), table_name='client_observations')
    op.drop_index(op.f('ix_client_observations_survey_id'), table_name='client_observations')
    op.drop_index(op.f('ix_client_observations_id'), table_name='client_observations')
    op.drop_index(op.f('ix_client_observations_client_mac'), table_name='client_observations')
    op.drop_index(op.f('ix_client_observations_bssid'), table_name='client_observations')
    op.drop_table('client_observations')
    # ### end Alembic commands ###
