"""create_missing_tables

Revision ID: 921fcd9f8c9d
Revises: b55517630efd
Create Date: 2026-08-06 03:59:03.938756+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921fcd9f8c9d'
down_revision: Union[str, Sequence[str], None] = 'b55517630efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deauth_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_profile_id', sa.Integer(), nullable=True),
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_deauth_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deauth_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deauth_devices_client_mac'), 'deauth_devices', ['client_mac'], unique=True)
    op.create_index('ix_deauth_devices_device_profile_id', 'deauth_devices', ['device_profile_id'], unique=False)
    op.create_index(op.f('ix_deauth_devices_id'), 'deauth_devices', ['id'], unique=False)
    op.create_index(op.f('ix_deauth_devices_status'), 'deauth_devices', ['status'], unique=False)
    
    op.create_table('deauth_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deauth_device_id', sa.Integer(), nullable=True),
    sa.Column('client_mac', sa.String(length=32), nullable=True),
    sa.Column('device_profile_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('packets_sent', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deauth_logs_client_mac'), 'deauth_logs', ['client_mac'], unique=False)
    op.create_index(op.f('ix_deauth_logs_deauth_device_id'), 'deauth_logs', ['deauth_device_id'], unique=False)
    op.create_index(op.f('ix_deauth_logs_device_profile_id'), 'deauth_logs', ['device_profile_id'], unique=False)
    op.create_index(op.f('ix_deauth_logs_id'), 'deauth_logs', ['id'], unique=False)
    op.create_index('ix_deauth_logs_requested_at', 'deauth_logs', ['requested_at'], unique=False)
    op.create_index('ix_deauth_logs_success', 'deauth_logs', ['success'], unique=False)
    
    op.create_table('deauth_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deauth_device_id', sa.Integer(), nullable=True),
    sa.Column('client_mac', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deauth_queue_client_mac'), 'deauth_queue', ['client_mac'], unique=False)
    op.create_index(op.f('ix_deauth_queue_deauth_device_id'), 'deauth_queue', ['deauth_device_id'], unique=False)
    op.create_index(op.f('ix_deauth_queue_id'), 'deauth_queue', ['id'], unique=False)
    op.create_index(op.f('ix_deauth_queue_status'), 'deauth_queue', ['status'], unique=False)
    op.create_index('ix_deauth_queue_status_priority', 'deauth_queue', ['status', 'priority'], unique=False)
    
    op.create_table('device_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_profiles_client_mac'), 'device_profiles', ['client_mac'], unique=True)
    op.create_index(op.f('ix_device_profiles_id'), 'device_profiles', ['id'], unique=False)
    
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_name', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    
    op.create_table('client_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('bssid', sa.String(length=32), nullable=True),
    sa.Column('ssid', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('client_mac', sa.String(length=32), nullable=False),
    sa.Column('client_vendor', sa.String(length=255), server_default='Unknown Manufacturer', nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('signal_dbm', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('coordinate_source', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_observations_bssid'), 'client_observations', ['bssid'], unique=False)
    op.create_index(op.f('ix_client_observations_client_mac'), 'client_observations', ['client_mac'], unique=False)
    op.create_index(op.f('ix_client_observations_id'), 'client_observations', ['id'], unique=False)
    op.create_index(op.f('ix_client_observations_import_batch_id'), 'client_observations', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_client_observations_survey_id'), 'client_observations', ['survey_id'], unique=False)
    op.create_index(op.f('ix_client_observations_timestamp'), 'client_observations', ['timestamp'], unique=False)
    
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('inserted_records', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batch_id'), 'import_batch', ['id'], unique=False)
    op.create_index(op.f('ix_import_batch_survey_id'), 'import_batch', ['survey_id'], unique=False)
    
    op.create_table('observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('bssid', sa.String(), nullable=True),
    sa.Column('ssid', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), server_default='Unknown Manufacturer', nullable=False),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('signal_dbm', sa.Integer(), nullable=True),
    sa.Column('encryption', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_bssid'), 'observation', ['bssid'], unique=False)
    op.create_index(op.f('ix_observation_id'), 'observation', ['id'], unique=False)
    op.create_index(op.f('ix_observation_import_batch_id'), 'observation', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_observation_survey_id'), 'observation', ['survey_id'], unique=False)
    op.create_index(op.f('ix_observation_timestamp'), 'observation', ['timestamp'], unique=False)
    
    # ### Added bssid_alert table ###
    op.create_table('bssid_alert',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bssid', sa.String(length=32), nullable=False),
        sa.Column('alert_type', sa.String(length=50), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('previous_area', sa.String(length=255), nullable=True),
        sa.Column('current_area', sa.String(length=255), nullable=True),
        sa.Column('import_batch_id', sa.Integer(), nullable=True),
        sa.Column('observation_id', sa.Integer(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bssid_alert_bssid'), 'bssid_alert', ['bssid'], unique=False)
    op.create_index(op.f('ix_bssid_alert_id'), 'bssid_alert', ['id'], unique=False)
    op.create_index(op.f('ix_bssid_alert_is_read'), 'bssid_alert', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop bssid_alert table and its indexes
    op.drop_index(op.f('ix_bssid_alert_is_read'), table_name='bssid_alert')
    op.drop_index(op.f('ix_bssid_alert_id'), table_name='bssid_alert')
    op.drop_index(op.f('ix_bssid_alert_bssid'), table_name='bssid_alert')
    op.drop_table('bssid_alert')
    
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_observation_timestamp'), table_name='observation')
    op.drop_index(op.f('ix_observation_survey_id'), table_name='observation')
    op.drop_index(op.f('ix_observation_import_batch_id'), table_name='observation')
    op.drop_index(op.f('ix_observation_id'), table_name='observation')
    op.drop_index(op.f('ix_observation_bssid'), table_name='observation')
    op.drop_table('observation')
    op.drop_index(op.f('ix_import_batch_survey_id'), table_name='import_batch')
    op.drop_index(op.f('ix_import_batch_id'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_client_observations_timestamp'), table_name='client_observations')
    op.drop_index(op.f('ix_client_observations_survey_id'), table_name='client_observations')
    op.drop_index(op.f('ix_client_observations_import_batch_id'), table_name='client_observations')
    op.drop_index(op.f('ix_client_observations_id'), table_name='client_observations')
    op.drop_index(op.f('ix_client_observations_client_mac'), table_name='client_observations')
    op.drop_index(op.f('ix_client_observations_bssid'), table_name='client_observations')
    op.drop_table('client_observations')
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.drop_table('survey')
    op.drop_index(op.f('ix_device_profiles_id'), table_name='device_profiles')
    op.drop_index(op.f('ix_device_profiles_client_mac'), table_name='device_profiles')
    op.drop_table('device_profiles')
    op.drop_index('ix_deauth_queue_status_priority', table_name='deauth_queue')
    op.drop_index(op.f('ix_deauth_queue_status'), table_name='deauth_queue')
    op.drop_index(op.f('ix_deauth_queue_id'), table_name='deauth_queue')
    op.drop_index(op.f('ix_deauth_queue_deauth_device_id'), table_name='deauth_queue')
    op.drop_index(op.f('ix_deauth_queue_client_mac'), table_name='deauth_queue')
    op.drop_table('deauth_queue')
    op.drop_index('ix_deauth_logs_success', table_name='deauth_logs')
    op.drop_index('ix_deauth_logs_requested_at', table_name='deauth_logs')
    op.drop_index(op.f('ix_deauth_logs_id'), table_name='deauth_logs')
    op.drop_index(op.f('ix_deauth_logs_device_profile_id'), table_name='deauth_logs')
    op.drop_index(op.f('ix_deauth_logs_deauth_device_id'), table_name='deauth_logs')
    op.drop_index(op.f('ix_deauth_logs_client_mac'), table_name='deauth_logs')
    op.drop_table('deauth_logs')
    op.drop_index(op.f('ix_deauth_devices_status'), table_name='deauth_devices')
    op.drop_index(op.f('ix_deauth_devices_id'), table_name='deauth_devices')
    op.drop_index('ix_deauth_devices_device_profile_id', table_name='deauth_devices')
    op.drop_index(op.f('ix_deauth_devices_client_mac'), table_name='deauth_devices')
    op.drop_table('deauth_devices')
    # ### end Alembic commands ###
